export default {
  FORTUNE_COOKIE: "fortuneCookie",
  ROOMATE_AGREEMENT: "roomateAgreement",
  PROPERTY: "property",
  TRAIN: "train",
  ROCKET: "rocket",
  CAR: "car",
  SCOOTER: "scooter",
  BOOK: "book",
  WIFI: "wifi",
  WINE: "wine",
  RING: "ring",
  JAIL: "jail",
  START: "start",
  GO_TO_JAIL: "goToJail",
  CHILL: "chill",
}